<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as BaseVerifier;

class VerifyCsrfToken extends BaseVerifier
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        //银联，支付宝相关

        'order/pay/alipay/notify',
        'order/pay/wechat/notify',

        //app接口相关请求
        'api/*',

        //验证发布作品金额
        'user/goodsCashValid',
    ];

    public function handle($request, \Closure $next)
    {
        //获取token不匹配异常(session过期造成)
        try{
             return parent::handle($request, $next); // TODO: Change the autogenerated stub
        }catch (\Exception $e){
            return redirect()->back();
        }

    }
}
